# express
# 192.168.130.128:18081
version: "3.9"
services:
    mongo1:
        image: mongo:${MONGODB_VERSION}
        container_name: mongo1_${MONGODB_VERSION}
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 123456
        ports:
            - 37017:27017
    mongo2:
        image: mongo:${MONGODB_VERSION}
        container_name: mongo2_${MONGODB_VERSION}
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 123456
        ports:
            - 37018:27017
    mongo3:
        image: mongo:${MONGODB_VERSION}
        container_name: mongo3_${MONGODB_VERSION}
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 123456
        ports:
            - 37019:27017
    mongo-express1:
        image: mongo-express:${MONGO_EXPRESS_VERSINO}
        restart: always
        ports:
            - 18081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
            ME_CONFIG_MONGODB_SERVER: mongo1_${MONGODB_VERSION}
        links:
            - mongo1
        depends_on:
            - mongo1
    mongo-express2:
        image: mongo-express:${MONGO_EXPRESS_VERSINO}
        restart: always
        ports:
            - 18082:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
            ME_CONFIG_MONGODB_SERVER: mongo2_${MONGODB_VERSION}
        links:
            - mongo2
        depends_on:
            - mongo2
    mongo-express3:
        image: mongo-express:${MONGO_EXPRESS_VERSINO}
        restart: always
        ports:
            - 18083:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
            ME_CONFIG_MONGODB_SERVER: mongo3_${MONGODB_VERSION}
        links:
            - mongo3
        depends_on:
            - mongo3