version: "3.9"
services:
    database:
        image: mysql:${VERSION}
        container_name: mysq_single_${VERSION}
        volumes:
            - /home/Joe/work/Docker/mysql/single/data:/var/lib/mysql:rw
        ports:
            - 13306:3306
        environment:
            MYSQL_ROOT_PASSWORD: '123456'
        command:
            mysqld
