package advertisement

const (
	FetchVersionOfADOfCarouselReq_ = "1"
	FetchVersionOfADOfCarouselRsp_ = "2"
	FetchIdListOfADOfCarouselReq_  = "3"
	FetchIdListOfADOfCarouselRsp_  = "4"
	FetchRecordsOfADOfCarouselReq_ = "5"
	FetchRecordsOfADOfCarouselRsp_ = "6"
	FetchVersionOfADOfDealsReq_    = "7"
	FetchVersionOfADOfDealsRsp_    = "8"
	FetchIdListOfADOfDealsReq_     = "9"
	FetchIdListOfADOfDealsRsp_     = "10"
	FetchRecordsOfADOfDealsReq_    = "11"
	FetchRecordsOfADOfDealsRsp_    = "12"
	FetchVersionOfADOfHotsReq_     = "13"
	FetchVersionOfADOfHotsRsp_     = "14"
	FetchIdListOfADOfHotsReq_      = "15"
	FetchIdListOfADOfHotsRsp_      = "16"
	FetchRecordsOfADOfHotsReq_     = "17"
	FetchRecordsOfADOfHotsRsp_     = "18"
	FetchVersionOfADOfBarbecueReq_ = "19"
	FetchVersionOfADOfBarbecueRsp_ = "20"
	FetchIdListOfADOfBarbecueReq_  = "21"
	FetchIdListOfADOfBarbecueRsp_  = "22"
	FetchRecordsOfADOfBarbecueReq_ = "23"
	FetchRecordsOfADOfBarbecueRsp_ = "24"
	FetchVersionOfADOfSnacksReq_   = "25"
	FetchVersionOfADOfSnacksRsp_   = "26"
	FetchIdListOfADOfSnacksReq_    = "27"
	FetchIdListOfADOfSnacksRsp_    = "28"
	FetchRecordsOfADOfSnacksReq_   = "29"
	FetchRecordsOfADOfSnacksRsp_   = "30"
)
