package advertisement

const (
	FetchVersionOfADOfCarouselReq_    = "1"
	FetchVersionOfADOfCarouselRsp_    = "2"
	FetchIdListOfADOfCarouselReq_     = "3"
	FetchIdListOfADOfCarouselRsp_     = "4"
	FetchRecordsOfADOfCarouselReq_    = "5"
	FetchRecordsOfADOfCarouselRsp_    = "6"
	InsertRecordOfADOfCarouselReq_    = "7"
	InsertRecordOfADOfCarouselRsp_    = "8"
	SoftDeleteRecordOfADOfCarouselReq = "9"
	SoftDeleteRecordOfADOfCarouselRsp = "10"
	UpdateRecordOfADOfCarouselReq     = "11"
	UpdateRecordOfADOfCarouselRsp     = "12"
	// FetchADOfCarouselReq_               = "1"
	// FetchADOfCarouselRsp_               = "2"
	// FetchVersionOfADOfCarouselReq_      = "3"
	// FetchVersionOfADOfCarouselRsp_      = "4"
	// FetchADOfDealsOfTodayReq_           = "5"
	// FetchADOfDealsOfTodayRsp_           = "6"
	// FetchVersionOfADOfDealsOfTodayReq_  = "7"
	// FetchVersionOfADOfDealsOfTodayRsp_  = "8"
	// FetchADOfHotDealsReq_               = "9"
	// FetchADOfHotDealsRsp_               = "10"
	// FetchVersionOfADOfHotDealsReq_      = "11"
	// FetchVersionOfADOfHotDealsRsp_      = "12"
	// FetchADOfBBQProductsReq_            = "13"
	// FetchADOfBBQProductsRsp_            = "14"
	// FetchVersionOfADOfBBQProductsReq_   = "15"
	// FetchVersionOfADOfBBQProductsRsp_   = "16"
	// FetchADOfSnackProductsReq_          = "17"
	// FetchADOfSnackProductsRsp_          = "18"
	// FetchVersionOfADOfSnackProductsReq_ = "19"
	// FetchVersionOfADOfSnackProductsRsp_ = "20"
	// FetchIdListOfADOfCarouselReq_       = "21"
	// FetchIdListOfADOfCarouselRsp_       = "22"
)
