# http://192.168.130.129:8848/nacos/
# default user&password nacos&nacos

# nacos-docker-compose-up
# docker compose -f nacos-single.yml up -d

#nacos-docker-compose-down
# docker compose -f nacos-single.yml down

version: "3.9"
services:
    database:
        image: nacos/nacos-server:${VERSION}
        container_name: nacos_server_single_${VERSION}
        volumes:
            - /home/Joe/work/Docker/nacos/single/data:/home/nacos/data
            - /home/Joe/work/Docker/nacos/single/logs:/home/nacos/logs
        ports:
            - 8848:8848
            - 9848:9848
        environment:
            - MODE=standalone
        command:
            nacos-server
