# express
# 192.168.130.128:18081
version: "3.9"
services:
    mongodb:
        image: mongo:${MONGODB_VERSION}
        container_name: Mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 123456
        ports:
            - 27001:27017
    mongo-express1:
        image: mongo-express:${MONGO_EXPRESS_VERSINO}
        container_name: Mongo-Express
        restart: always
        ports:
            - 18081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
            ME_CONFIG_BASICAUTH_USERNAME: root
            ME_CONFIG_BASICAUTH_PASSWORD: 123456
            ME_CONFIG_MONGODB_SERVER: mongodb
        links:
            - mongodb
        depends_on:
            - mongodb