package code

import "net/http"

var en = map[int]string{
	Success:                     "success",        // success
	http.StatusOK:               "success",        // success
	InternalError:               "internal error", // 服务器问题导致的错误
	ServiceError:                "service error",  // 服务问题导致的错误
	NotAuthenticated:            "not authenticated",
	NoSuchUser:                  "no such user",
	UserExists:                  "user exists",
	MemberInGroup:               "member in group",
	MemberNotInGroup:            "member not in group",
	LogonFailure:                "logon failure",
	AccountDisable:              "account disable",
	NoUserSessionKey:            "no user session key",
	NotLoggedOn:                 "not logged on",
	UserProfileLoad:             "user profile load",
	PasswordTooShort:            "password too short",
	PasswordTooRecent:           "password too recent",
	PasswordTooLong:             "password too long",
	AccountExpired:              "account expired",
	PasswordMustChange:          "password must change",
	BadUserName:                 "bad user name",
	NetworkBusy:                 "network busy",
	UnexpectedNetworkError:      "unexpected network error",
	NetworkAccessDenied:         "network access denied",
	NoNetwork:                   "no network",
	GracefulDisconnect:          "graceful disconnect",
	ConnectionRefuse:            "connection refuse",
	NetworkUnreachable:          "network unreachable",
	ConnectionAborted:           "connection aborted",
	IncorrectAddress:            "incorrect address",
	InvalidData:                 "invalid data",
	NoData:                      "no data",
	InvalidToken:                "invalid token",
	DataChecksumError:           "data checksum error",
	DatabaseDoesNotExist:        "database does not exist",
	BadConfiguration:            "bad configuration",
	UnsupportedType:             "unsupported type",
	InvalidDataType:             "invalid data type",
	ResourceDataNotFound:        "resource data not found",
	DatabaseFailure:             "database failure",
	DatabaseFull:                "database full",
	AppDataNotFound:             "app data not found",
	AppDataExpired:              "app data expired",
	AppDataCorrupted:            "app data corrupt",
	AppDataLimitExceeded:        "app data limit exceeded",
	BadTokenType:                "bad token type",
	TokenAlreadyInUse:           "token already in use",
	InvalidTime:                 "invalid time",
	DataSourceProtocolError:     "data source protocol error",
	NotSupported:                "not supported",
	Busy:                        "busy",
	RequestAborted:              "request aborted",
	NoToken:                     "no token",
	InvalidEncryptAlgorithm:     "invalid encrypt algorithm",
	EncryptingPayloadFailure:    "encrypting payload failure",
	DecryptingPayloadFailure:    "decrypting payload failure",
	InvalidCertificateSignature: "invalid certification signature",
	UnHandledException:          "unhandled exception",
	ServiceRequestTimeout:       "service request timeout",
	ObjectAlreadyExists:         "object already exists",
	ObjectInList:                "object in list",
	NotConnected:                "not connected",
	EntryNotFound:               "entry not found",
	EntryAlreadyExists:          "entry already exists",
	MissingData:                 "missing data",
	NotInitialized:              "not initialized",
	AlreadyInitialized:          "already initialized",
	AlreadyCompleted:            "already completed",
	AccessDenied:                "access denied",
	Empty:                       "empty",
	NotEmpty:                    "not empty",
}
