package code

import "net/http"

var zh = map[int]string{
	Success:                     "操作成功", // success
	http.StatusOK:               "操作成功", // success
	InternalError:               "内部错误", // 服务器问题导致的错误
	ServiceError:                "服务错误", // 服务问题导致的错误
	NotAuthenticated:            "不允许操作, 未授权",
	NoSuchUser:                  "没有此用户",
	UserExists:                  "用户已存在",
	MemberInGroup:               "用户已经在组中",
	MemberNotInGroup:            "用户不在组中",
	LogonFailure:                "用户名或者密码错误",
	AccountDisable:              "帐号已被冻结, 不允许登录",
	NoUserSessionKey:            "没有会话密钥, 或者密钥已过期",
	NotLoggedOn:                 "不允许操作, 帐号未授权",
	UserProfileLoad:             "无法加载用户详情",
	PasswordTooShort:            "密码太短, 不符合规范",
	PasswordTooRecent:           "修改密码过于频繁",
	PasswordTooLong:             "密码太长, 不符合规范",
	AccountExpired:              "帐号已过期, 无法使用",
	PasswordMustChange:          "强制重置密码, 重置密码后才允许登录",
	BadUserName:                 "用户名错误, 不合法的用户名",
	NetworkBusy:                 "网络繁忙, 稍后再试",
	UnexpectedNetworkError:      "未知网络错误",
	NetworkAccessDenied:         "网络访问被拒",
	NoNetwork:                   "没有网络",
	GracefulDisconnect:          "网络连接已断开",
	ConnectionRefuse:            "服务器拒绝网络连接",
	NetworkUnreachable:          "网络不可到达",
	ConnectionAborted:           "本机终止网络连接",
	IncorrectAddress:            "地址不正确, 无法使用",
	InvalidData:                 "数据错误",
	NoData:                      "没有数据",
	InvalidToken:                "格式错误 或者 不正确的token",
	DataChecksumError:           "数据检验失败",
	DatabaseDoesNotExist:        "数据库不存在",
	BadConfiguration:            "配置无效或者非法",
	UnsupportedType:             "不支持的数据类型",
	InvalidDataType:             "提供的数据类型无法识别 或者 非法的",
	ResourceDataNotFound:        "未找到资源, 如 图片无法找到",
	DatabaseFailure:             "数据操作失败, 不能读写数据库",
	DatabaseFull:                "数据库已满负载",
	AppDataNotFound:             "找不到应用程序的cache数据",
	AppDataExpired:              "应用程序的cache数据已超时",
	AppDataCorrupted:            "应用程序的cache数据已被损坏",
	AppDataLimitExceeded:        "应用程序的cache数据超出预留空间",
	BadTokenType:                "token可被系统识别, 但用途错误, 当前应用无法使用",
	TokenAlreadyInUse:           "token已被使用 或者 占用",
	InvalidTime:                 "时间格式错误, 是无效 或者 非法的",
	DataSourceProtocolError:     "数据源协议错误, 非法的, 无法识别的协议",
	NotSupported:                "不支持的请求, 无法处理请求",
	Busy:                        "请求的资源已被占用",
	RequestAborted:              "请求被中止",
	NoToken:                     "请求协议中没有提供token",
	InvalidEncryptAlgorithm:     "非法的加密算法",
	EncryptingPayloadFailure:    "加密payload失败",
	DecryptingPayloadFailure:    "解密payload失败",
	InvalidCertificateSignature: "非法的签名, 签名无法被应用识别",
	UnHandledException:          "程序存在未处理异常",
	ServiceRequestTimeout:       "服务器处理请求超时",
	ObjectAlreadyExists:         "对象已存在 或者 已被占用",
	ObjectInList:                "对象已存在于列表中",
	NotConnected:                "网络连接不存在, 网络未连接",
	EntryNotFound:               "找不到Entry",
	EntryAlreadyExists:          "Entry已存在, 或者被占用",
	MissingData:                 "请求的数据不在缓存中, 缓存中未找到相应数据",
	NotInitialized:              "提供的对象未初始化",
	AlreadyInitialized:          "提供的对象已完成初始化",
	AlreadyCompleted:            "操作已完成",
	AccessDenied:                "拒绝访问",
	Empty:                       "为空, 没有值",
	NotEmpty:                    "不为空, 有值",
}
