
# docker exec -it 290 /bin/bash
# cat /etc/gitlab/initial_root_password
# git branch -m main master

version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ee:${VERSION}'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '8929:8929'
      - '2224:22'
    volumes:
      - /home/joe/work/Docker/gitlab/config:/etc/gitlab
      - /home/joe/work/Docker/gitlab/log:/var/log/gitlab
      - /home/joe/work/Docker/gitlab/data/:/var/opt/gitlab
    shm_size: '256m'